"""create model education, specialization, room

Revision ID: 41642eda29a2
Revises: 8dfb0cc791f3
Create Date: 2025-04-29 22:51:54.690855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41642eda29a2'
down_revision = '8dfb0cc791f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('educations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('room',
    sa.Column('id', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('specializations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('quantity_patient', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('specializations')
    op.drop_table('room')
    op.drop_table('educations')
    # ### end Alembic commands ###
