"""create model category disease and diagnose disease

Revision ID: f7821d4f34dd
Revises: 3d2a4ead71d2
Create Date: 2025-04-30 08:33:45.779425

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f7821d4f34dd'
down_revision = '3d2a4ead71d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category_disease',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_disease_name', sa.String(length=255), nullable=False),
    sa.Column('category_disease_description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('diagnose_disease',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('diagnose_disease_name', sa.String(length=255), nullable=False),
    sa.Column('diagnose_disease_description', sa.Text(), nullable=False),
    sa.Column('category_disease_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['category_disease_id'], ['category_disease.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('diagnose_disease')
    op.drop_table('category_disease')
    # ### end Alembic commands ###
